### PR TITLE
refactoring

### PR DESCRIPTION
**Pull request by BitPatty**
Lots of refactoring to have a more consistent coding style throughout the project and to improve readability.

This includes:
- Added the solution file and moved the project to the according subdirectory. Bundling the solution file makes it way easier to restore the project, especially if it uses external packages.
- Added `.editorconfig` for consistent autoformatting in VS
- Migrated from packages.config to PackageReference, see https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference for details
- Ensuring consistent naming scheme for private/public members, with private members starting with an underscore. This makes it easier to access and work with private members
- Put all properties to the beginning of the class and reorder them according to visibility and/or complexity
- Removed redundant `this` keywords
- Simplified getters / setters where applicable
- Mark all todos to `@TODO` for easier searching
- Mark properties as readonly where applicable
- Optimized some LINQ calls
- Fixed capitalization for methods, see https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions for details
- Renamed overriden parameters to match the base class
- Used String.Format where it improved readability
- Removed some redundant variables
- Restored build path
- Added more  `@TODOs `

Also maybe it would be a good idea to add .Core and .UpdateManager to the repo, would make it easier to manage the dependency paths.

Note that your plugin doesn't work on other machines, since `ProfilePath` is never set. Are you already loading it from an existing configuration file?

### CODE REVIEW

**Comment by ROMaster2** [comment]
The entire Models/Features directory needs a rewrite. I copied it from the video scanner and it's been working well enough to leave alone, but it's neither maintainable nor readable. I tried rewriting it recently and got overwhelmed. I'll try to improve it during beta.

The underscore for private field/properties is good. I just didn't want to use camelCase since that gets easily mixed up in variables.

A few of the `this.` were kept to improve readability but it's not a problem to remove.

https://git.io/fp5eb -- Not a clue. I don't know if it's even being used.
https://git.io/fp5v5 -- If someone can tell me the proper way of doing this, I'm all ears.

Otherwise it looks great. Thanks for the help!

**Comment by ROMaster2** [comment]
Had to revert. It completely broke building everything. Did you build the component through LiveSplit?

**Comment by BitPatty** [comment]
Oh you of course have to rereference core and updatemanager, I don't build it with LiveSplit

That's the problem with not having solution files in the repository..

**Comment by BitPatty** [comment]
What's the error message anyway

**Pull request merged**
